create table if not exists public.portfolio_visitors (
  id bigint generated by default as identity primary key,
  ip_hash text not null unique,
  ip_address text,
  ip_masked text not null,
  location_label text not null default 'Localisation inconnue',
  city text,
  region text,
  country text,
  visit_count integer not null default 1,
  device_type text not null default 'Inconnu',
  browser text not null default 'Inconnu',
  user_agent text,
  language text,
  timezone text,
  screen_size text,
  last_page_path text,
  last_page_title text,
  last_referrer text,
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now()
);

create table if not exists public.portfolio_visit_events (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  ip_address text,
  ip_masked text not null,
  location_label text not null default 'Localisation inconnue',
  city text,
  region text,
  country text,
  device_type text not null default 'Inconnu',
  browser text not null default 'Inconnu',
  page_path text,
  page_title text,
  referrer text,
  language text,
  timezone text,
  screen_size text,
  user_agent text,
  visited_at timestamptz not null default now()
);

create index if not exists portfolio_visitors_last_seen_idx on public.portfolio_visitors (last_seen desc);
create index if not exists portfolio_visitors_country_idx on public.portfolio_visitors (country);
create index if not exists portfolio_visit_events_visited_at_idx on public.portfolio_visit_events (visited_at desc);
create index if not exists portfolio_visit_events_ip_hash_idx on public.portfolio_visit_events (ip_hash);

alter table public.portfolio_visitors enable row level security;
alter table public.portfolio_visit_events enable row level security;

drop policy if exists "portfolio_visitors_service_only" on public.portfolio_visitors;
drop policy if exists "portfolio_visit_events_service_only" on public.portfolio_visit_events;

create policy "portfolio_visitors_service_only"
on public.portfolio_visitors
for all
using (false)
with check (false);

create policy "portfolio_visit_events_service_only"
on public.portfolio_visit_events
for all
using (false)
with check (false);
